import Head from "next/head";
import HomeScreen from "../screens/HomeScreen";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <HomeScreen/>
    </div>
  );
}
