import Head from "next/head";
import Image from "next/image";
import Footer from "../components/front/Footer";
import Header from "./../components/front/Header";
import { Button } from "react-bootstrap";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={"main"}>
        <div className="container">
          <h2>Home page</h2>
          <Button variant="danger">Warning</Button>
        </div>
      </main>
      <Footer />
    </div>
  );
}
